version: '3.8'

services:
  php:
    build: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://za:root@mysql:3306/gestion_stock"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'gestion_stock'
      MYSQL_USER: 'za'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
